seed: 20 #
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx64_train.npy'
  conditional: True
  labels_subset: #
    - 0
    - 1
  labels: '../../data_processed/params_IllustrisTNG.txt'
  transforms: 'imgwisestandardscale+randfliprot'
  labels_normalize: True

architecture:
  encoder_config: #
    encoder_model: imgwisestandardscale
    encoder_kwargs: {}
    ckpt: ~
  decoder_config: #
    decoder_model: deterministic+cond
    decoder_kwargs:
      mid_dim: 5
      loss_type: mse
    ckpt: ~

train:
  epochs: 150 #
  batch_size: 20 #
  optimizer: Adam #
  learning_rate: 5e-4 #

