seed: 20
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx64_train.npy'
  conditional: True
  labels_subset:
    - 0
    - 1
  labels: '../../data_processed/params_IllustrisTNG.txt'
  transforms: 'minmax+randfliprot'
  labels_normalize: True

architecture:
  model: explicitconditional
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  use_cond_dim_for_block: True
  non_linear_conditional_embedding: True
  unet_dim: 64
  circular_conv: True

diffusion:
  beta_schedule: linear_beta_schedule
  schedule_args:
    beta_start: 0.0001
    beta_end: 0.02
  timesteps: 1000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 150
  batch_size: 20
  optimizer: Adam
  learning_rate: 2e-4
  loss_args:
    loss_version: standard
    recon_loss: False
    prior_loss: False
    loss_type: huber
    recon_weight: 1.0
    prior_weight: 1.0
