seed: 20
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx64_train.npy'
  conditional: True
  labels_subset:
    - 0
    - 1
  labels: '../../data_processed/params_IllustrisTNG.txt'
  transforms: 'standardscale+randfliprot'
  normfile: 'results/misc/IllustrisTNGLH_norms.pkl'
  normkey: 'Maps_Mcdm_IllustrisTNG_LH_z=0.00.npy'
  labels_normalize: True


architecture:
  model: baseline
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  unet_dim: 64
  base2fourier:
    b2fstart: 6
    b2fend: 8
    b2fstep: 1

diffusion:
  beta_schedule: log_custom_schedule
  schedule_args: {}
  timesteps: 1000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 150
  batch_size: 40
  optimizer: Adam
  learning_rate: 2e-4
  loss_args:
    loss_version: reconstruction #default: standard
    loss_type: huber
    recon_loss: True
    recon_norm: None
    recon_weight: 1.0
    prior_loss: False
    prior_weight: 1.0
