data:
  path: '../../data_processed/dust/dust_train.fits'
  conditional: False
  transforms: 'None'

architecture:
  model: baseline
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  unet_dim: 64

diffusion:
  beta_schedule: linear_beta_schedule
  schedule_args:
    beta_start: 0.0001
    beta_end: 0.02
  timesteps: 1000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 7
  batch_size: 40
  optimizer: Adam
  learning_rate: 2e-4
  loss_type: huber
