data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx64_train.npy'
  conditional: False

architecture:
  model: baseline
  dim_mults:
    - 1
    - 2
    - 4
  init_conv: True

diffusion:
  beta_schedule: linear_beta_schedule
  schedule_args:
    beta_start: 0.0001
    beta_end: 0.02
  timesteps: 2000
  sampler_args:
      type: 'loss_aware'
      history: 10
      nstart: 1000


train:
  epochs: 1
  batch_size: 40
  optimizer: Adam #do
  learning_rate: 1e-3
  loss_type: huber
