seed: 20
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx256_train.npy'
  conditional: True
  labels_subset: 'all' 
  labels: '../../data_processed/params_IllustrisTNG.txt'
  transforms: 'minmax+randfliprot'

architecture:
  model: baseline
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  unet_dim: 32

diffusion:
  beta_schedule: linear_beta_schedule
  schedule_args:
    beta_start: 0.0001
    beta_end: 0.02
  timesteps: 2000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 300
  batch_size: 40
  optimizer: Adam
  learning_rate: 2e-4
  loss_type: huber

resume_ckp: 'checkpoint_40000.pt'
resume_id: 'uno3xgc6'
resume_name: 'Run_10-26_21-27'
