seed: 20
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx64_train.npy'
  conditional: True
  labels_subset:
    - 0
    - 1
  labels: '../../data_processed/params_IllustrisTNG.txt'
  transforms: 'standardscale+randfliprot'
  normfile: 'results/misc/illustristnglh_norms.pkl'
  normkey: 'maps_mcdm_illustristng_lh_z=0.00.npy'
  labels_normalize: True

architecture:
  model: explicitconditional
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  unet_dim: 64
  pk_embedding: True
  image_size: 64

diffusion:
  beta_schedule: log_custom_schedule
  schedule_args: {}
  timesteps: 1000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 150
  batch_size: 20
  optimizer: Adam
  learning_rate: 2e-4
  optimizer_reset: True
  loss_args:
    loss_version: reconstruction #default: standard
    loss_type: huber
    recon_loss: True
    recon_norm: None
    recon_weight: 1.0
    prior_loss: False
    prior_weight: 1.0

