seed: 20
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx64_train.npy'
  conditional: True
  labels_subset:
    - 0
    - 1
  labels: '../../data_processed/params_IllustrisTNG.txt'
  transforms: 'imgwisestandardscale+randfliprot'
  labels_normalize: True

architecture:
  model: explicitconditional
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  use_cond_dim_for_block: True
  non_linear_conditional_embedding: True
  unet_dim: 64
  base2fourier:
    b2fstart: -5
    b2fend: 0
    b2fstep: 1
  encoder_config:
    encoder_model: imgwisestandardscale
    encoder_kwargs: {}
    ckpt: ~
  decoder_config:
    decoder_model: deterministic+cond
    decoder_kwargs:
      mid_dim: 5
      loss_type: mse
      freeze: False
    ckpt: ~

diffusion:
  beta_schedule: linear_beta_schedule
  schedule_args:
    beta_start: 0.0001
    beta_end: 0.01
  timesteps: 1000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 150
  batch_size: 20
  optimizer: Adam
  learning_rate: 2e-4
  optimizer_reset: True
  loss_kwargs:
    diff_loss_type: huber
    recon_weight: 1.0
    prior_weight: 1.0
